name: Build and Test

on: [push, pull_request]

jobs:
    crypto:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install circom
              run: |
                  sudo wget -O /usr/bin/circom https://github.com/iden3/circom/releases/download/v2.1.9/circom-linux-amd64
                  sudo chmod +x /usr/bin/circom
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install snarkjs
              run: npm install -g snarkjs
            - name: Install rapidsnark
              run: |
                  git clone https://github.com/iden3/rapidsnark.git
                  cd rapidsnark
                  git submodule init
                  git submodule update
                  ./build_gmp.sh host
                  mkdir build_prover && cd build_prover
                  cmake .. -DTARGET_PLATFORM=aarch64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../package_aarch64
                  make -j4 && make install
            - name: Install dependencies
              run: |
                  cd crypto
                  npm install
            - name: Build circuits
              run: |
                  cd crypto
                  npm run build
                  cd semaphore_cpp
                  make
                  ls
            - name: Run tests
              run: |
                  cd crypto
                  npm test
    ddh:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build
              run: |
                  cd crypto-ddh
                  ./autogen.sh
                  ./configure
                  make
            - name: Test
              run: |
                  cd crypto-ddh
                  ./tests
